title: Genieva.github.io
description: Build well, live well
google_analytics: UA-54457392-1
show_downloads: false
theme: jekyll-theme-architect
div class: my_work

#gems:
#  - jekyll-mentions

sass:
  sass_dir: assets/css
  style: :nested
